# -*- coding: utf-8 -*-
"""22-Feb-BoysScout-Evening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDpqOQ4w7vJ97jxl2wnF7RjM7PJqJs4U
"""

class Masjid():

    religion = "Islam",
    qibla = "Khana-e-Kaba",

    def __init__(self, name, location, minar = 1, gumbad = 1) -> None:
        self.name = name,
        self.location = location,
        self.minar = minar
        self.gumbad = gumbad

    def azan (self, timing):
        return f"(Azan-e-{timing})"

    def namaz (self, timing):
        return f"(jamat-e-{timing})"

obj1 = Masjid("Bilal Masjid", "Karachi", 1, 1)
print(obj1.__dict__)


obj2 = Masjid("Masjid Usman", "Lahore", 2, 2)
print(obj2.__dict__)



obj3 = Masjid("Shahi Masjid", "Thatta", 1, 99)
print(obj3.__dict__)

print(Masjid.religion, Masjid.qibla)
print(obj1.religion, obj1.qibla)
print(obj2.religion, obj2.qibla)
print(obj3.religion, obj3.qibla)

class Parent():
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

    def show_info(self):
        print(f"Name: {self.name}, Age: {self.age}")

    def speak(self, sound):
        print(f"Parent {self.name} says {sound}")

    def listen(self, sound):
        print(f"Parent {self.name} listens {sound}")

    def eat(self, food):
        print(f"Parent {self.name} eats {food}")

    def sleep(self, hours):
        print(f"Parent {self.name} sleeps for {hours} hours")

class Child(Parent):
  pass


c1 = Child("Qasim", 20)
print(c1.name)
print(c1.age)
c1.show_info()
c1.speak("Hello")
c1.listen("Hello")
c1.eat("Pizza")
c1.sleep(8)

class Parent():
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

    def show_info(self):
        print(f"Name: {self.name}, Age: {self.age}")

    def speak(self, sound):
        print(f"Parent {self.name} says {sound}")

    def listen(self, sound):
        print(f"Parent {self.name} listens {sound}")

    def eat(self, food):
        print(f"Parent {self.name} eats {food}")

    def sleep(self, hours):
        print(f"Parent {self.name} sleeps for {hours} hours")

class Child(Parent):
  def __init__(self, name, age, language, hobby):
    super().__init__(name, age)
    self.language = language
    self.hobby = hobby
  def reading (self, book):
    print(f"{self.name} is reading {book}")

  def programming (self, language):
    print(f"{self.name} is programming in {language}")


c1 = Child("Qasim", 20, "urdu", "circket")
print(c1.name)
print(c1.age)
c1.show_info()
c1.speak("Hello")
c1.listen("Hello")
c1.eat("Pizza")
c1.sleep(8)
c1.reading("Quran")
c1.programming("Python")

class Father():
  pass


class Mother():
  pass

class Child(Father, Mother):
  pass

class Father():
  def __init__(self, name, age) -> None:
    self.name = name
    self.age = age
    self.hair_color = "Brown"
    self.eye_color = "Black"

  def show_info(self):
    print(f"Name: {self.name}, Age: {self.age}")

  def speak(self, sound):
    print(f"Father {self.name} says {sound}")


class Mother():
  def __init__(self, name , age ) -> None:
    self.name = name
    self.age = age
    self.hair_color = "Black"
    self.eye_color = "Blue"

  def show_info(self):
    print(f"Name: {self.name}, Age: {self.age}")

  def speak(self, sound):
    print(f"Mother {self.name} says {sound}")

  def cook(self, food):
    print(f"Mother {self.name} cooks {food}")


class Child( Mother, Father):
  pass


c2=Child("Qasim", 20)
# print(f"name: {c2.name}")
# print(c2.age)
c2.show_info()
c2.speak("Hello")
c2.cook("Pizza")
print(c2.__dict__)





"""# Class Car
# Methods(Play Music, Climate Control, Cruise control)

# 5 Brands Classes
# Toyota (Must) with engine
# Tesla (Must) with electric motor
# Porch
# Ferrai(2 doors)
# Rolls Royce

# Objects for your own cars
"""